# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20170131_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
    ]
